### PR TITLE
Update nock to ^1.1.0

### PR DESCRIPTION
**Pull request by arikon**
Also:
- Enable connections to the localhost resources for the `nock` (disabled by default since `1.0.0`)
- Add repository and bugs sections to the `package.json`
- Fix path to `mocha`: no need to specify full path in `node_modules`

### CODE REVIEW

**Comment by arikon** [comment]
@rprieto Would you mind making a review?

**Comment by rprieto** [comment]
Thanks a lot @arikon, just tested it and it looks great :+1: 

Do you mind rebasing it into a single commit? (or a least squashing `update Nock` and `Enable connections` together since the build fails in between)

**Comment by arikon** [comment]
@rprieto Done

**Comment by rprieto** [comment]
Thanks again, I'll release a new version tomorrow!

**Comment by arikon** [comment]
@rprieto Would you mind releasing an updated version?

**Comment by arikon** [comment]
@rprieto :+1:

**Comment by arikon** [comment]
@rprieto So, what about release? ;)

**Comment by rprieto** [comment]
Thanks for the reminder, just published `v1.0.1` :)

**Comment by arikon** [comment]
@rprieto Thanks!

PS: BTW, according to semver it should be minor release

**Comment by arikon** [comment]
@rprieto I can't see tags and changes in `package.json` in the repo. Did you forget to make `git push origin master --tags`?

**Comment by rprieto** [comment]
Why a minor? (I don't think there is any new functionality is there?)
And yes sorry I published but probably didn't push, I'll do that after the weekend.

**Comment by arikon** [comment]
@rprieto `real-nock` proxies `nock` functionaliy, and that was a big updated (major, in fact).

**Comment by rprieto** [comment]
D'oh, you're right. Worth force-deleting the `1.0.1` version you think? Otherwise :+1: to keep in mind for next time.

**Comment by arikon** [comment]
I'm not sure of force deleting. You decide ;)

13.03.2015, 10:50, "Romain Prieto" notifications@github.com:

> D'oh, you're right. Worth force-deleting the 1.0.1 version you think? Otherwise  to keep in mind for next time.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Pull request merged**
